### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by adamstep** [mhassanpur/takehome-202409#1]
Hi @mhassanpur , thanks for the submission. I reviewed and overall looked good! A couple of things I noticed though:

- The instructions for docker compose are not complete. After running the containers, I needed to exec into the server to run migrations and load the fixture data. That should probably be mentioned in the readme.
- In the UI, when I press "Delete", there's no confirmation dialog. It's easy to delete a team member by accident.
- When there's only 1 team member, there's a grammatical error in the label, it should say "You have 1 team member" (no 's').

Can you address these issues? Thanks!

**Comment by mhassanpur** [comment]
Hi @adamstep - Thanks for the feedback! I've addressed these issues in a new branch, `bug/adamstep-feedback`. Here's the PR: https://github.com/mhassanpur/takehome-202409/pull/2
